apiVersion: v1
kind: Secret
metadata:
  name: kuba-be-secret
  namespace: kuba
type: Opaque
stringData:
  DB_USERNAME: "postgres"
  DB_PASSWORD: "change-me"
  JWT_SECRET: "change-me-super-secure-jwt-secret"
